// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/codepzj/gin-template/conf"
	"github.com/codepzj/gin-template/internal/handler"
	"github.com/codepzj/gin-template/internal/repository"
	"github.com/codepzj/gin-template/internal/server"
	"github.com/codepzj/gin-template/internal/service"
)

// Injectors from wire.go:

// wireApp 初始化应用
func wireApp(cfg *conf.Config) (*server.HttpServer, error) {
	data := repository.NewData()
	serviceService := service.NewService(data)
	handlerHandler := handler.NewHandler(serviceService)
	ginEngine := server.NewGin(handlerHandler)
	httpServer := server.NewHttpServer(ginEngine, cfg)
	return httpServer, nil
}
