port: 2574 # 服务端口

mysql:
  dsn: "root:123456@tcp(localhost:23306)/note?charset=utf8mb4&parseTime=True&loc=Local"
  slow_sql_threshold: 200 # 慢查询日志,单位ms
  log_level: info # silent/error/warn/info

  
